[package]
name = "httpbuddy"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
env_logger = { version = "0.11.8", features = ["auto-color", "humantime"] }
reqwest = { version = "0.12.15", features = ["blocking"] }
